// Splits the monolithic MarkQuiz.jsx data section into per-route modules
// so each screen downloads only the questions and translation it needs.
// Run: node scripts/gen-data.mjs
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { BANK, KJV, WEB, HIN, XREF, HXREF } from "./_data-source.mjs";

const OUT = new URL("../src/data/", import.meta.url);
const dir = (p) => { mkdirSync(new URL(p, OUT), { recursive: true }); };
const write = (p, body) => {
  const url = new URL(p, OUT);
  writeFileSync(url, body);
  return Buffer.byteLength(body);
};

rmSync(new URL("chapters/", OUT), { recursive: true, force: true });
rmSync(new URL("scripture/", OUT), { recursive: true, force: true });
dir("chapters/");
dir("scripture/");

const banner = "// Generated by scripts/gen-data.mjs — do not edit by hand.\n";
const sizes = {};

// ---------- per-chapter question modules ----------
for (const c of BANK) {
  const body = banner + `export default ${JSON.stringify({ ch: c.ch, title: c.title, qs: c.qs })};\n`;
  sizes[`chapters/ch-${c.ch}.js`] = write(`chapters/ch-${c.ch}.js`, body);
}

// ---------- scripture, one module per translation ----------
for (const [name, book] of [["web", WEB], ["kjv", KJV], ["hin", HIN]]) {
  sizes[`scripture/${name}.js`] = write(`scripture/${name}.js`, banner + `export default ${JSON.stringify(book)};\n`);
}

// ---------- cross-references (small, ships with scripture) ----------
sizes["xref.js"] = write("xref.js",
  banner + `export const XREF = ${JSON.stringify(XREF)};\nexport const HXREF = ${JSON.stringify(HXREF)};\n`);

// ---------- eager metadata: titles and counts only, no question text ----------
const counts = Object.fromEntries(BANK.map((c) => [c.ch, c.qs.length]));
const meta = banner + `export const CHAPTERS = ${JSON.stringify(
  BANK.map((c) => ({ ch: c.ch, title: c.title, count: c.qs.length, hi: c.qs.every((q) => q.hi) }))
)};
export const TOTAL = ${BANK.reduce((n, c) => n + c.qs.length, 0)};
export const COUNTS = ${JSON.stringify(counts)};
`;
sizes["meta.js"] = write("meta.js", meta);

const total = Object.values(sizes).reduce((a, b) => a + b, 0);
const kb = (n) => (n / 1024).toFixed(1) + " KB";
for (const [k, v] of Object.entries(sizes)) console.log(kb(v).padStart(10), k);
console.log("-".repeat(34));
console.log(kb(total).padStart(10), `total across ${Object.keys(sizes).length} modules`);
